### ISSUE TITLE
Wordpress crash when activating plugin

### ISSUE THREAD

**Issue by daveCordero** [cloudcogsio/woocommerce-omnipay-powertranz-3ds2-gateway#2]
Hi @cloudcogsio, 

I just installed your plugin on my wordpress site and it shows the error in the image:

- https://imgur.com/a/0PW90iZ

Thanks for your support.

**Comment by cloudcogsio** [comment]
Did you install dependencies before creating the plugin?
Also, PHP 7.4 is required.
You should be able to tell the specific error by reviewing your PHP error logs.

**Comment by daveCordero** [comment]
**> Did you install dependencies before creating the plugin?**
Where can I see the dependencies needed ?

**> You should be able to tell the specific error by reviewing your PHP error logs.** 
Should I consider this log error? 
_[Tue Oct 25 06:03:27.474319 2022] [core:crit] [pid 15130] (13)Permission denied: [client 192.241.205.51:34304] AH00529: /home/tasesmasterweb/public_html/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/tasesmasterweb/public_html/' is executable_

Thank you!

**Comment by daveCordero** [comment]
Hi @cloudcogsio 
¿Is it necessary to have an OmniPay account in order to use this plugin?

**Comment by cloudcogsio** [comment]
> Hi @cloudcogsio ¿Is it necessary to have an OmniPay account in order to use this plugin?

No, Omnipay is just another PHP library. 
Note, this isn't a complete, "ready to use" plugin.

You need to:
1. Download this project
2. Install the dependencies using composer
3. Run "make_woocommerce_plugin.php" which will create a zip file.
4. Install the created zip file as a plugin in Wordpress.
