### ISSUE TITLE
Plugin only authorizes payment, even when set to "Transaction Type": "Charge"

### ISSUE THREAD

**Issue by w33zy** [cloudcogsio/woocommerce-omnipay-powertranz-3ds2-gateway#3]
Hello,
thanks for this plugin.

Have you ever come across a situation where all "authorize & capture" transactions are only ever processed as "authorize" on FAC's backend? This is the second plugin that I have tried that is giving me this result and the FAC support team is insisting the issue is not theirs.

**Comment by cloudcogsio** [comment]
Hi, no I have not come across this situation.
If you're getting the issue with different plugins then most likely it's a configuration issue on their end.

Are you experiencing this with both test and live credentials?
If possible, try another set of test credentials to see if you get the same issue.

**Comment by w33zy** [comment]
Hey thanks for responding. The issue, in my case, is happening with your plugin and another one. So I am going to say the issue is on their end.

I resolved this issue by setting the plugin to capture payments, the client is shipping a product so authorizing the capturing payment when the product is shipped is a viable solution.

BTW, that feature of capturing payment when changing the status to "completed" is really good feature. Can I assume this will work programatically, e.g., setting up a WP CRON job to set all "pending" orders to "completed" will run the capture transaction for each order?

**Comment by cloudcogsio** [comment]
Hi, I have not tested this, but I assume once your job uses the **`woocommerce_order_status_*`** hooks to make the changes, then it should perform the captures. The capture on status change depends on the **`woocommerce_order_status_changed`** hook.

**Comment by w33zy** [comment]
OK, I'll into that.
Also, sincerely, thanks for the plugin.
