### ISSUE TITLE
Integration with Wordpress 6.4.3 and Woocommerce 8.6.1

### ISSUE THREAD

**Issue by er3webdesign** [cloudcogsio/woocommerce-omnipay-powertranz-3ds2-gateway#4]
Hello, when I try to activate this plugin to my site it generates a critical error. Is there any update for this??

**Comment by cloudcogsio** [comment]
Note, this isn't a complete, "ready to use" plugin.

You need to:

1. Download this project
2. Install the dependencies using composer
3. Run "make_woocommerce_plugin.php" which will create a zip file.
4. Install the created zip file as a plugin in Wordpress.

**Comment by er3webdesign** [comment]
Thank you for your response!! I proceeded to do so, but the dependencies are not installed correctly and I get errors of missing files and incompatibility with PHP 8.0 and above. I used the updated files in your most recent repository, and same thing happened. Let me know if we can chat to let you know more about the issue.

**Comment by cloudcogsio** [comment]
Change the minimum stability to 'dev' before running composer install.
